apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0fd531ef5754e021c
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: ebs-static
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: presistance-volume
          mountPath: /var/www/html
  volumes:
    - name: presistance-volume
      persistentVolumeClaim:
        claimName: ebs-static
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c