apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels: 
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32000