apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
  template:
    metadata:
      name: nginx
      labels:
        project: roboshop
        environment: dev
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
