apiVersion: v1
kind: Pod
metadata:
  name: emptyDir
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /var/logs/nginx
      name: nginx-logs
  - name: almalinux
    image: almalinux:9
    volumeMounts:
    - mountPath: /var/logs/almalinux
      name: nginx-logs
      readOnly: true
  volumes:
  - name: nginx-logs
    emptyDir:
      sizeLimit: 500Mi